export const companiesData = [
  {
    name: "Ipak Yo'li",
    ticker: "IPKY",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/2.webp",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7039920002?page=1&page_size=8&start_date=2024-06-27&end_date=2024-06-27",
  },
  {
    name: "Trastbank” XAB",
    ticker: "TRSB",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/TrastBank.png",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7033480003?page=1&page_size=8&start_date=2024-06-26&end_date=2024-06-26",
  },
  {
    name: "Hamkorbank",
    ticker: "HMKB",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/Hamkor1.png",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7011340005?page=1&page_size=8&start_date=2024-06-26&end_date=2024-06-26",
  },
  {
    name: "Ipoteka-bank",
    ticker: "IPTB",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/Ipateka_bank_1.png",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7054570005?page=1&page_size=8&start_date=2024-06-26&end_date=2024-06-26",
  },
  {
    name: "Sanoatqurilishbank",
    ticker: "SQBN",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/SQB_.png",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7037560008/?page=1&page_size=8&start_date=2024-06-26&end_date=2024-06-26",
  },
  {
    name: "O'zmetkombinat",
    ticker: "UZMK",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/Logo_UMK_V_EN.png",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7033480003?page=1&page_size=8&start_date=2024-06-26&end_date=2024-06-26",
  },
  {
    name: "Qizilqumsement",
    ticker: "QZSM",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/logo.svg",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7029000005/?page=1&page_size=8&start_date=2024-06-27&end_date=2024-06-27",
  },
  {
    name: "Kvarts",
    ticker: "KVTS",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/kvarts_logo.png",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7025770007/?page=1&page_size=8&start_date=2024-06-27&end_date=2024-06-27",
  },
  {
    name: "O'zbekinvest",
    ticker: "UZINP",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/uzbinv.png",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7056921008/?page=1&page_size=8&start_date=2024-06-27&end_date=2024-06-27",
  },
  {
    name: "O'zbektelekom",
    ticker: "UZTL",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/uztelecom_square_blue.png",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7033480003?page=1&page_size=8&start_date=2024-06-26&end_date=2024-06-26",
  },
  {
    name: "O'zRTXB",
    ticker: "URTS",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/uzex.svg",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7043200003/?page=1&page_size=8&start_date=2024-06-26&end_date=2024-06-26",
  },
  {
    name: "UzAuto Motors",
    ticker: "UZMT",
    market: "STK",
    logo: "https://openinfo.uz/en/media/organization_logos/uzauto.jpg",
    url: "https://new-api.openinfo.uz/api/v2/iuzse/trade-results/UZ7003040001/?page=1&page_size=8&start_date=2024-06-26&end_date=2024-06-26",
  },
];
